# 使用更小的Python基础镜像
FROM dockerproxy.slpchat.top/python:3.9-alpine

# 设置工作目录
WORKDIR /app

# 复制 webhook.py 文件到工作目录
COPY webhook.py .

# 安装所需依赖
RUN pip install flask requests

# 安装docker客户端
RUN apk add --no-cache docker-cli

# 启动命令
CMD ["python", "webhook.py"]