events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # 全局配置
    sendfile        on;
    keepalive_timeout  65;

    # 移除全局包含的 allowed_ips.conf
    # include /etc/nginx/conf.d/allowed_ips.conf;

    server {
        listen 80;
        server_name localhost;

        # 配置真实IP识别
        set_real_ip_from 192.168.65.1;  # 添加 Docker 主机 IP
        real_ip_header X-Real-IP;
        real_ip_recursive on;

        # 应用IP访问限制
        satisfy all;
        include /etc/nginx/conf.d/allowed_ips.conf;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        # 添加拒绝访问的处理
        error_page 403 /403.html;
        location = /403.html {
            root   /usr/share/nginx/html;
            internal;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}